### ISSUE TITLE
Compatibility with screen readers

### ISSUE THREAD

**Issue by slavanga** [ten1seven/what-input#27]
I just found this comment about what input on [a11yproject.com](http://a11yproject.com/posts/never-remove-css-outlines/):

> Consider this third solution as a last resort. Some browser/screen reader combinations fire mouse events, which could cause outlines to disappear while using this method.

Can someone confirm or deny if what input is working correctly with screen readers?

**Comment by ten1seven** [comment]
Hi @slavanga, thanks for sending this article! Like it mentions, **What Input** doesn't set styles itself -- it sets an attribute on the body, leaving styling up to the individual author. In that sense, the script itself doesn't violate any issues with what events a screen reader fires.

However, the suggested usage for styling...

``` css
/**
 * set a default :focus style
 */
a:focus {
  outline: 3px dotted #06c;
}

/*
 * remove :focus style via What Input using progressive enhancement
 * so :focus isn't left broken if JavaScript fails
 */
[data-whatinput="mouse"] a:focus,
[data-whatinput="touch"] a:focus {
  outline: none;
}
```

...could cause the issue noted in the article. I haven't done specific testing with screen readers and I wish the article had pointed out what combinations caused issues. Since the choice is in your hands, you could leave default styling in place and enhance keyboard focus styles alone, like:

``` css
[data-whatinput="keyboard"] *:focus {
  outline: 3px dotted #06c;
}
```

What Input was born in the agency world where tight design control includes the common request for `:focus { outline: none; }`.The script is a response to providing that control for designers while maintaining accessibility. _There can be a tradeoff_. I wrote a [post on this topic](https://viget.com/inspire/how-to-implement-accessibility-in-agency-projects-part-1). If you have time I invite you to check it out and welcome your comments.
